apiVersion: v1
kind: Service
metadata:
  name: sae-app-service
  namespace: sae-production
  labels:
    app: sae-app
spec:
  type: NodePort
  selector:
    app: sae-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
