global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'addrservice-monitor'

scrape_configs:
  - job_name: 'addrservice'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['addrservice:8080']
    scrape_interval: 15s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']